### Variables
@baseUrl = http://localhost:8080/v1
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIyYTM5NmZkNS0wZmQyLTRkYmQtYTg3NC1mYTY1YTRmZDc1ZDciLCJlbWFpbCI6ImRldmVsb3BAZ21haWwuY29tIiwiZXhwIjoxNzY1MzEyNDcyLCJpYXQiOjE3NjUzMTE1NzJ9.V2EykT8ePgriljSJXXeFhVPnPazV49p0z9kv9h4XDGQ
@enroll_token = autohost-enr_yduO8volPIA6aFTegI7aCaWGZjxe9xQA3Y3PAY6tEdg

### Generate Enrollment Token
POST {{baseUrl}}/enrollments/generate
Authorization: Bearer {{access_token}}
Content-Type: application/json

### Enroll Node
POST {{baseUrl}}/enrollments/enroll
Content-Type: application/json

{
  "enroll_token": "{{enroll_token}}",
  "hostname": "pi-lab03",
  "ip_local": "192.168.1.100",
  "os": "linux",
  "arch": "arm64",
  "version_agent": "1.0.0"
}
