@baseUrl = http://localhost:8080/v1
@node_token = autohost-node_uhX9PjAIyygWsKImMYKbgjkMoWnbbHDcWfKAcqypwgI


### Send Heartbeat
POST {{baseUrl}}/heartbeats/heartbeat
Authorization: Bearer {{node_token}}
Content-Type: application/json
