@baseUrl = http://localhost:8080/v1
@node_token = autohost-node_HaeEcy9zv1zyIdlXqdcS4dk8ipcuSN8ZGRrMHDzXamo

### Post node_with_metrics
POST {{baseUrl}}/node-metrics/metrics
Authorization: Bearer {{node_token}}
Content-Type: application/json

{
    "cpu_usage_percent": 55.5,
    "memory_total_bytes": 2048,
    "memory_used_bytes": 4960,
    "memory_available_bytes": 40960,
    "memory_usage_percent": 55.5,
    "disk_total_bytes": 81920,
    "disk_used_bytes": 40960,
    "disk_available_bytes": 40960,
    "disk_usage_percent": 50.0
}
