// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.1
// source: node_agent.proto

package nodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgentService_RegisterCommands_FullMethodName = "/node_agent.v1.NodeAgentService/RegisterCommands"
	NodeAgentService_Connect_FullMethodName          = "/node_agent.v1.NodeAgentService/Connect"
)

// NodeAgentServiceClient is the client API for NodeAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAgentServiceClient interface {
	// Agent streams its commands; server upserts them all, then acks.
	RegisterCommands(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RegisterCommandRequest, RegisterCommandsResponse], error)
	// Long-lived bidirectional stream used to dispatch jobs and receive results.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, ServerMessage], error)
}

type nodeAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentServiceClient(cc grpc.ClientConnInterface) NodeAgentServiceClient {
	return &nodeAgentServiceClient{cc}
}

func (c *nodeAgentServiceClient) RegisterCommands(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RegisterCommandRequest, RegisterCommandsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[0], NodeAgentService_RegisterCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterCommandRequest, RegisterCommandsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_RegisterCommandsClient = grpc.ClientStreamingClient[RegisterCommandRequest, RegisterCommandsResponse]

func (c *nodeAgentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[1], NodeAgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_ConnectClient = grpc.BidiStreamingClient[NodeMessage, ServerMessage]

// NodeAgentServiceServer is the server API for NodeAgentService service.
// All implementations must embed UnimplementedNodeAgentServiceServer
// for forward compatibility.
type NodeAgentServiceServer interface {
	// Agent streams its commands; server upserts them all, then acks.
	RegisterCommands(grpc.ClientStreamingServer[RegisterCommandRequest, RegisterCommandsResponse]) error
	// Long-lived bidirectional stream used to dispatch jobs and receive results.
	Connect(grpc.BidiStreamingServer[NodeMessage, ServerMessage]) error
	mustEmbedUnimplementedNodeAgentServiceServer()
}

// UnimplementedNodeAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServiceServer struct{}

func (UnimplementedNodeAgentServiceServer) RegisterCommands(grpc.ClientStreamingServer[RegisterCommandRequest, RegisterCommandsResponse]) error {
	return status.Error(codes.Unimplemented, "method RegisterCommands not implemented")
}
func (UnimplementedNodeAgentServiceServer) Connect(grpc.BidiStreamingServer[NodeMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeAgentServiceServer) mustEmbedUnimplementedNodeAgentServiceServer() {}
func (UnimplementedNodeAgentServiceServer) testEmbeddedByValue()                          {}

// UnsafeNodeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServiceServer will
// result in compilation errors.
type UnsafeNodeAgentServiceServer interface {
	mustEmbedUnimplementedNodeAgentServiceServer()
}

func RegisterNodeAgentServiceServer(s grpc.ServiceRegistrar, srv NodeAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgentService_ServiceDesc, srv)
}

func _NodeAgentService_RegisterCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServiceServer).RegisterCommands(&grpc.GenericServerStream[RegisterCommandRequest, RegisterCommandsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_RegisterCommandsServer = grpc.ClientStreamingServer[RegisterCommandRequest, RegisterCommandsResponse]

func _NodeAgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServiceServer).Connect(&grpc.GenericServerStream[NodeMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_ConnectServer = grpc.BidiStreamingServer[NodeMessage, ServerMessage]

// NodeAgentService_ServiceDesc is the grpc.ServiceDesc for NodeAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node_agent.v1.NodeAgentService",
	HandlerType: (*NodeAgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterCommands",
			Handler:       _NodeAgentService_RegisterCommands_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Connect",
			Handler:       _NodeAgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node_agent.proto",
}
