// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: node_agent.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_DEFAULT CommandType = 0
	CommandType_COMMAND_TYPE_CUSTOM  CommandType = 1
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_DEFAULT",
		1: "COMMAND_TYPE_CUSTOM",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_DEFAULT": 0,
		"COMMAND_TYPE_CUSTOM":  1,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_agent_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_node_agent_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{0}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_RUNNING   JobStatus = 0
	JobStatus_JOB_STATUS_COMPLETED JobStatus = 1
	JobStatus_JOB_STATUS_FAILED    JobStatus = 2
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_RUNNING",
		1: "JOB_STATUS_COMPLETED",
		2: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_RUNNING":   0,
		"JOB_STATUS_COMPLETED": 1,
		"JOB_STATUS_FAILED":    2,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_node_agent_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_node_agent_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{1}
}

type RegisterCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // validated against the auth token server-side
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          CommandType            `protobuf:"varint,4,opt,name=type,proto3,enum=node_agent.v1.CommandType" json:"type,omitempty"`
	ScriptPath    string                 `protobuf:"bytes,5,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"` // only set for COMMAND_TYPE_CUSTOM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCommandRequest) Reset() {
	*x = RegisterCommandRequest{}
	mi := &file_node_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandRequest) ProtoMessage() {}

func (x *RegisterCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandRequest.ProtoReflect.Descriptor instead.
func (*RegisterCommandRequest) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCommandRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterCommandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterCommandRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterCommandRequest) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_DEFAULT
}

func (x *RegisterCommandRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

type RegisterCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    int32                  `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"` // total commands upserted in this batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCommandsResponse) Reset() {
	*x = RegisterCommandsResponse{}
	mi := &file_node_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandsResponse) ProtoMessage() {}

func (x *RegisterCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandsResponse.ProtoReflect.Descriptor instead.
func (*RegisterCommandsResponse) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCommandsResponse) GetRegistered() int32 {
	if x != nil {
		return x.Registered
	}
	return 0
}

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NodeMessage_JobResult
	//	*NodeMessage_Heartbeat
	Payload       isNodeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_node_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMessage) GetPayload() isNodeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NodeMessage) GetJobResult() *JobResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() *HeartbeatPayload {
	if x != nil {
		if x, ok := x.Payload.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isNodeMessage_Payload interface {
	isNodeMessage_Payload()
}

type NodeMessage_JobResult struct {
	JobResult *JobResultPayload `protobuf:"bytes,1,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type NodeMessage_Heartbeat struct {
	Heartbeat *HeartbeatPayload `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*NodeMessage_JobResult) isNodeMessage_Payload() {}

func (*NodeMessage_Heartbeat) isNodeMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_ExecuteJob
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_node_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetExecuteJob() *ExecuteJobPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecuteJob); ok {
			return x.ExecuteJob
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_ExecuteJob struct {
	ExecuteJob *ExecuteJobPayload `protobuf:"bytes,1,opt,name=execute_job,json=executeJob,proto3,oneof"`
}

func (*ServerMessage_ExecuteJob) isServerMessage_Payload() {}

type JobResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=node_agent.v1.JobStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResultPayload) Reset() {
	*x = JobResultPayload{}
	mi := &file_node_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResultPayload) ProtoMessage() {}

func (x *JobResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResultPayload.ProtoReflect.Descriptor instead.
func (*JobResultPayload) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{4}
}

func (x *JobResultPayload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResultPayload) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_RUNNING
}

func (x *JobResultPayload) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobResultPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPayload) Reset() {
	*x = HeartbeatPayload{}
	mi := &file_node_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPayload) ProtoMessage() {}

func (x *HeartbeatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPayload.ProtoReflect.Descriptor instead.
func (*HeartbeatPayload) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ExecuteJobPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CommandName   string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	CommandType   CommandType            `protobuf:"varint,3,opt,name=command_type,json=commandType,proto3,enum=node_agent.v1.CommandType" json:"command_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteJobPayload) Reset() {
	*x = ExecuteJobPayload{}
	mi := &file_node_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteJobPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobPayload) ProtoMessage() {}

func (x *ExecuteJobPayload) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobPayload.ProtoReflect.Descriptor instead.
func (*ExecuteJobPayload) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteJobPayload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteJobPayload) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *ExecuteJobPayload) GetCommandType() CommandType {
	if x != nil {
		return x.CommandType
	}
	return CommandType_COMMAND_TYPE_DEFAULT
}

var File_node_agent_proto protoreflect.FileDescriptor

const file_node_agent_proto_rawDesc = "" +
	"\n" +
	"\x10node_agent.proto\x12\rnode_agent.v1\"\xb8\x01\n" +
	"\x16RegisterCommandRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1a.node_agent.v1.CommandTypeR\x04type\x12\x1f\n" +
	"\vscript_path\x18\x05 \x01(\tR\n" +
	"scriptPath\":\n" +
	"\x18RegisterCommandsResponse\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\x05R\n" +
	"registered\"\x9b\x01\n" +
	"\vNodeMessage\x12@\n" +
	"\n" +
	"job_result\x18\x01 \x01(\v2\x1f.node_agent.v1.JobResultPayloadH\x00R\tjobResult\x12?\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1f.node_agent.v1.HeartbeatPayloadH\x00R\theartbeatB\t\n" +
	"\apayload\"_\n" +
	"\rServerMessage\x12C\n" +
	"\vexecute_job\x18\x01 \x01(\v2 .node_agent.v1.ExecuteJobPayloadH\x00R\n" +
	"executeJobB\t\n" +
	"\apayload\"\x89\x01\n" +
	"\x10JobResultPayload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.node_agent.v1.JobStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"+\n" +
	"\x10HeartbeatPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x8c\x01\n" +
	"\x11ExecuteJobPayload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12=\n" +
	"\fcommand_type\x18\x03 \x01(\x0e2\x1a.node_agent.v1.CommandTypeR\vcommandType*@\n" +
	"\vCommandType\x12\x18\n" +
	"\x14COMMAND_TYPE_DEFAULT\x10\x00\x12\x17\n" +
	"\x13COMMAND_TYPE_CUSTOM\x10\x01*T\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x00\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x01\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x022\xc1\x01\n" +
	"\x10NodeAgentService\x12d\n" +
	"\x10RegisterCommands\x12%.node_agent.v1.RegisterCommandRequest\x1a'.node_agent.v1.RegisterCommandsResponse(\x01\x12G\n" +
	"\aConnect\x12\x1a.node_agent.v1.NodeMessage\x1a\x1c.node_agent.v1.ServerMessage(\x010\x01B;Z9github.com/arturo/autohost-cloud-api/internal/grpc/nodepbb\x06proto3"

var (
	file_node_agent_proto_rawDescOnce sync.Once
	file_node_agent_proto_rawDescData []byte
)

func file_node_agent_proto_rawDescGZIP() []byte {
	file_node_agent_proto_rawDescOnce.Do(func() {
		file_node_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_agent_proto_rawDesc), len(file_node_agent_proto_rawDesc)))
	})
	return file_node_agent_proto_rawDescData
}

var file_node_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_node_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_node_agent_proto_goTypes = []any{
	(CommandType)(0),                 // 0: node_agent.v1.CommandType
	(JobStatus)(0),                   // 1: node_agent.v1.JobStatus
	(*RegisterCommandRequest)(nil),   // 2: node_agent.v1.RegisterCommandRequest
	(*RegisterCommandsResponse)(nil), // 3: node_agent.v1.RegisterCommandsResponse
	(*NodeMessage)(nil),              // 4: node_agent.v1.NodeMessage
	(*ServerMessage)(nil),            // 5: node_agent.v1.ServerMessage
	(*JobResultPayload)(nil),         // 6: node_agent.v1.JobResultPayload
	(*HeartbeatPayload)(nil),         // 7: node_agent.v1.HeartbeatPayload
	(*ExecuteJobPayload)(nil),        // 8: node_agent.v1.ExecuteJobPayload
}
var file_node_agent_proto_depIdxs = []int32{
	0, // 0: node_agent.v1.RegisterCommandRequest.type:type_name -> node_agent.v1.CommandType
	6, // 1: node_agent.v1.NodeMessage.job_result:type_name -> node_agent.v1.JobResultPayload
	7, // 2: node_agent.v1.NodeMessage.heartbeat:type_name -> node_agent.v1.HeartbeatPayload
	8, // 3: node_agent.v1.ServerMessage.execute_job:type_name -> node_agent.v1.ExecuteJobPayload
	1, // 4: node_agent.v1.JobResultPayload.status:type_name -> node_agent.v1.JobStatus
	0, // 5: node_agent.v1.ExecuteJobPayload.command_type:type_name -> node_agent.v1.CommandType
	2, // 6: node_agent.v1.NodeAgentService.RegisterCommands:input_type -> node_agent.v1.RegisterCommandRequest
	4, // 7: node_agent.v1.NodeAgentService.Connect:input_type -> node_agent.v1.NodeMessage
	3, // 8: node_agent.v1.NodeAgentService.RegisterCommands:output_type -> node_agent.v1.RegisterCommandsResponse
	5, // 9: node_agent.v1.NodeAgentService.Connect:output_type -> node_agent.v1.ServerMessage
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_node_agent_proto_init() }
func file_node_agent_proto_init() {
	if File_node_agent_proto != nil {
		return
	}
	file_node_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeMessage_JobResult)(nil),
		(*NodeMessage_Heartbeat)(nil),
	}
	file_node_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_ExecuteJob)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_agent_proto_rawDesc), len(file_node_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_agent_proto_goTypes,
		DependencyIndexes: file_node_agent_proto_depIdxs,
		EnumInfos:         file_node_agent_proto_enumTypes,
		MessageInfos:      file_node_agent_proto_msgTypes,
	}.Build()
	File_node_agent_proto = out.File
	file_node_agent_proto_goTypes = nil
	file_node_agent_proto_depIdxs = nil
}
